### ISSUE TITLE
Consider requiring additional permission to `setBaseTokenURI`

### ISSUE THREAD

**Issue by pedrorivera** [Vanclief/solidity-imx-bridge#7]
https://github.com/Vanclief/solidity-imx-bridge/blob/e5e824b4bbcb82bd886138aeadbd0803b4d4977e/contracts/tokens/BridgeableNFT.sol#L29

I know you may have reasons to have it, but setBaseTokenURI is a major trust reliance on the owner of this contract. The owner can change a BoredApeish NFT to a Poop Emoji.

**Comment by Vanclief** [comment]
I understand, it is not a problem to remove it, as `BridgeableNFT` is just an example of an ERC20 extended to have the setBaseTokenURI option available. 

I agree that it will be better to remove it from this example as this should a premeditated decision, and not from someone copying over the code.

However just to play the devil advocate, unless your base TokenURI is an ipfs link, the owners of collections like [CyberKongz](https://etherscan.io/token/0x57a204aa1042f6e66dd7730813f4024114d74f37#readContract ) can still just change what the API is returning so instead of having a CyberKongz you have a CyberPoop without making any ETH transaction. 

Sadly, even if the link is an IPFS, the owners can as well just stop pinning the item on the network and unless other people start pining that item as well, you will go from having a BoredApe to having nothing.

Summary: NFTs are not really trust-less, so DYOR about who is behind them.

**Comment by Vanclief** [comment]
Updated contract: https://github.com/Vanclief/solidity-imx-bridge/commit/ae76cda8e3e02f14b7676519c13af04f8bdab10c
